apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: snipeit
spec:
  provider:
    vault:
      server: "http://vault.vault.svc:8200"
      path: snipeit
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: snipeit-eso
          serviceAccountRef:
            name: snipeit-eso
