{{- if .Values.vault.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mysql-app-secret
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef: { name: vault-backend, kind: SecretStore }
  target: { name: mysql-app-secret }
  refreshInterval: 1h
  data:
    - secretKey: MYSQL_ROOT_PASSWORD
      remoteRef: { key: mysql, property: MYSQL_ROOT_PASSWORD }
    - secretKey: MYSQL_PASSWORD
      remoteRef: { key: mysql, property: MYSQL_PASSWORD }
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: snipeit-app-secret
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef: { name: vault-backend, kind: SecretStore }
  target: { name: snipeit-app-secret }
  refreshInterval: 1h
  data:
    - secretKey: APP_KEY
      remoteRef: { key: app, property: APP_KEY }
    - secretKey: DB_PASSWORD
      remoteRef: { key: app, property: DB_PASSWORD }
{{- end }}
